/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b93e56cd98d6e65f4c1a35e255bd4f63)
interface __BaseEnv_Env {
	STUDIO_BASE_URL: "https://sathian.ai";
	SUPABASE_URL: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	TELEGRAM_BOT_TOKEN: string;
	TELEGRAM_CHAT_ID: string;
	TELEGRAM_TOPIC_ID: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "STUDIO_BASE_URL" | "SUPABASE_URL" | "SUPABASE_SERVICE_ROLE_KEY" | "TELEGRAM_BOT_TOKEN" | "TELEGRAM_CHAT_ID" | "TELEGRAM_TOPIC_ID">> {}
}
